version: '3.8'

networks:
  omnimarket.network:
    driver: bridge

services:
  omnimarket.mongodb:
    image: mongo:latest
    container_name: omnimarket.mongodb
    ports:
      - "27018:27017"
    networks:
      - omnimarket.network

  omnimarket.rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: omnimarket.rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - omnimarket.network

  catalog.api:
    image: omnimarket-catalog-api:latest
    container_name: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/OmniMarket.Catalog.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - omnimarket.mongodb
    networks:
      - omnimarket.network